version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask-app
    container_name: flask-container
    volumes:
        - ./:/usr/local/app
    ports:
      - 80:8000 # localport:dockerport
    # command: flask run --host=0.0.0.0
    command: /usr/local/bin/gunicorn run:app -b 0.0.0.0:8000 --chdir /usr/local/app
