version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask-app:latest
    container_name: flask-container
    ports:
      - 5001:5000 # localport:dockerport
    command: flask run --host=0.0.0.0
